### ISSUE TITLE
Some atf/kyua testcases implicitly require root privilege in order to run

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#100]
I ran kyua test as an unprivileged user to spot any potential permissions requirements issues, and several of the atf/kyua testcases failed when I ran them as !root. Here's a full list:

<pre>
local/atf/atf-c/detail/fs_test:mkdtemp_err
local/atf/atf-c/detail/fs_test:mkstemp_err
local/atf/atf-c/detail/sanity_test:inv
local/atf/atf-c/detail/sanity_test:post
local/atf/atf-c/detail/sanity_test:pre
local/atf/atf-c/detail/sanity_test:unreachable
local/atf/test-programs/result_test:result_to_file_fail
local/kyua-cli/cli/common_test:store_path__default__create_directory__fail
local/kyua-cli/engine/drivers/debug_test_test:TODO
local/kyua-cli/engine/drivers/run_tests_test:TODO
local/kyua-cli/engine/test_case_test:run_test_case__atf__required_user__atf__root__atf__ok
local/kyua-cli/engine/test_case_test:run_test_case__atf__required_user__atf__root__atf__skip
local/kyua-cli/engine/test_case_test:run_test_case__atf__required_user__atf__unprivileged__atf__drop
local/kyua-cli/engine/test_case_test:run_test_case__atf__required_user__atf__unprivileged__atf__ok
local/kyua-cli/engine/test_case_test:run_test_case__atf__required_user__atf__unprivileged__atf__skip
local/kyua-cli/integration/cmd_db_exec_test:store_flag__explicit__fail
local/kyua-cli/store/backend_test:detail__backup_database__fail_create
local/kyua-cli/utils/cmdline/ui_test:ui__screen_width__columns_empty__tty
local/kyua-cli/utils/cmdline/ui_test:ui__screen_width__columns_invalid__tty
local/kyua-cli/utils/cmdline/ui_test:ui__screen_width__columns_set__tty
local/kyua-cli/utils/fs/operations_test:mkdir_p__eacces
local/kyua-cli/utils/logging/operations_test:set_persistency__fail
local/kyua-cli/utils/sqlite/database_test:open__create__fail
local/kyua-cli/utils/text/templates_test:instantiate__files__output_error
local/kyua-testers/fs_test:cleanup__mount_point__busy
local/kyua-testers/fs_test:cleanup__mount_point__links
local/kyua-testers/fs_test:cleanup__mount_point__nested
local/kyua-testers/fs_test:cleanup__mount_point__overlayed
local/kyua-testers/fs_test:cleanup__mount_point__simple
local/kyua-testers/fs_test:cleanup__subdir__unprotect_symlink
local/kyua-testers/fs_test:unmount__fail
local/kyua-testers/fs_test:unmount__ok
local/kyua-testers/result_test:write__open_error
local/kyua-testers/run_test:fork_exec_wait__eacces
local/kyua-testers/run_test:fork_wait__unprivileged_both
local/kyua-testers/run_test:fork_wait__unprivileged_group
local/kyua-testers/run_test:fork_wait__unprivileged_user
local/kyua-testers/run_test:work_directory__mkdtemp_error
local/kyua-testers/run_test:work_directory__permissions
local/kyua-testers/run_test:work_directory__permissions_error
</pre>

**Comment by ngie-eign** [comment]
I accidentally pressed enter after submit. I updated the first comment with the full list :).

**Comment by ngie-eign** [comment]
This is where a lot of the errors are being generated:

<pre>
512 /// Creates a temporary directory for use by a subprocess.
513 ///
514 /// The temporary directory must be deleted with kyua_run_work_directory_leave.
515 ///
516 /// \param template Template of the work directory to create.  Should be a
517 ///      basename and must include the XXXXXX placeholder string.  The directory
518 ///      is created within the temporary directory specified by the TMPDIR
519 ///      environment variable or the builtin value.
520 /// \param uid User to set the owner of the directory to.
521 /// \param gid Group to set the owner of the directory to.
522 /// \param [out] out_work_directory Updated with a pointer to a dynamic string
523 ///      holding the path to the created work directory.  This must be passed as
524 ///      is to kyua_run_work_directory_leave, which takes care of freeing the
525 ///      memory.
526 ///
527 /// \return An error code if there is a problem creating the directory.
528 kyua_error_t
529 kyua_run_work_directory_enter(const char* template, const uid_t uid,
530                               const gid_t gid, char** out_work_directory)
...
550     if (uid != getuid() || gid != getgid()) {
551         if (chown(work_directory, uid, gid) == -1) {
552             error = kyua_libc_error_new(errno,
553                 "chown(%s, %ld, %ld) failed; uid is %ld and gid is %ld",
554                 work_directory, (long int)uid, (long int)gid,
555                 (long int)getuid(), (long int)getgid());
556             goto err_work_directory_file;
557         }
558     }
</pre>

This will work if someone has the ability to chown to a different user/group, but this only works if run via root.

From chown(2):

<pre>
     [EPERM]            The operation would change the ownership, but the
                        effective user ID is not the super-user.
</pre>

**Comment by jmmv** [comment]
Heh. That logic needs to be skipped when we already are an unprivileged user!

I'm shocked to not have encountered this earlier.
