### ISSUE TITLE
Plain/TAP handlers should support unprivileged execution

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#101]
I forgot that only the ATF handler handled `required_user="unprivileged"`; it would be nice if this support was extended to the plain/TAP handlers as well.

**Comment by jmmv** [comment]
The requirements are handled at the Kyua level, not at the testers level, so they are already generic.

Just set required_user="unprivileged" for the plain test program in the Kyuafile and this should work. See kyuafile(5).

**Comment by ngie-eign** [comment]
Yeah, I see where my PEBKAC issue was :/. Thanks for the help!
