### ISSUE TITLE
New version of kyua (0.9/0.10) regresses with the TAP tester

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#103]
I just tried out the latest version of kyua and unfortunately it regresses part of the TAP protocol :(... I've provided output and an example testcase below.

One potential fix is to implement the full regular expression handling for TAP starting from this line: https://github.com/jmmv/kyua/pull/91/files#diff-654631db1128f64ed26489bc0199e1a9L233

<pre>% kyua debug simple_test:main
kyua-tap-tester: Configuration variables not supported; ignoring 'has.cleanup=false'
kyua-tap-tester: Configuration variables not supported; ignoring 'unprivileged-user=tests'
1..1
ok - this does not work with kyua
simple_test:main  ->  broken: Reported plan differs from actual executed tests
% kyua debug simple_test_with_a_digit:main
kyua-tap-tester: Configuration variables not supported; ignoring 'has.cleanup=false'
kyua-tap-tester: Configuration variables not supported; ignoring 'unprivileged-user=tests'
1..1
ok - 1 # this works with kyua
simple_test_with_a_digit:main  ->  passed
% cat simple_test
#!/bin/sh

echo 1..1
echo "ok - this does not work with kyua"
% cat simple_test_with_a_digit
#!/bin/sh

echo 1..1
echo "ok - 1 # this works with kyua"
% cat Kyuafile
-- Automatically generated by bsd.test.mk.

syntax(2)

test_suite("FreeBSD")

tap_test_program{name="simple_test"}
tap_test_program{name="simple_test_with_a_digit"}
%</pre>

**Comment by jmmv** [comment]
Now I'm a bit confused. Let's take http://perldoc.perl.org/TAP/Parser/Grammar.html which you referenced in #85. The relevant definitions are:

```
test           ::= status positiveInteger? description? directive?
status         ::= 'not '? 'ok '
```

I missed the fact that `positiveInteger` is optional because otherwise the problem in #90 would not be fixed. However I now notice that the above says that `ok` with a trailing space (!) on a line by itself is fine but `ok` without the trailing space is not. Bleh...

**Comment by ngie-eign** [comment]
Yeah... it's unfortunate that the protocol in and of itself is so complicated :(..

**Comment by asomers** [comment]
Since Kyua doesn't care about the test number printed in the result line, this bug is actually pretty easy to fix.  Patch inline below

``` diff
--- ./testers/tap_parser.c.orig 2014-09-02 09:26:14.213788768 -0600
+++ ./testers/tap_parser.c  2014-09-02 09:27:55.140790602 -0600
@@ -302,7 +302,7 @@
     }

     regex_t preg;
-    int code = regcomp(&preg, "^(not )?ok[ \t-]+[0-9]+", REG_EXTENDED);
+    int code = regcomp(&preg, "^(not )?ok[ \t-]+[0-9]*", REG_EXTENDED);
     if (code != 0) {
         error = regex_error_new(code, &preg, "regcomp failed");
         goto out_input;
```

And the test cases:

``` diff
--- ./testers/tap_parser_test.c.orig    2014-09-02 09:34:51.773789162 -0600
+++ ./testers/tap_parser_test.c 2014-09-02 10:11:41.581788319 -0600
@@ -166,7 +166,7 @@
 ATF_TC_BODY(parse__ok__pass, tc)
 {
     const char* contents =
-        "1..7\n"
+        "1..8\n"
         "ok - 1\n"
         "    Some diagnostic message\n"
         "ok - 2 This test also passed\n"
@@ -175,13 +175,14 @@
         "not ok 4 # SKIP Some reason\n"
         "not ok 5 # TODO Another reason\n"
         "ok - 6 Doesn't make a difference SKIP\n"
-        "ok - 7 Doesn't make a difference either TODO\n";
+        "ok - 7 Doesn't make a difference either TODO\n"
+        "ok - #Without a test number is ok too\n";

     kyua_tap_summary_t summary;
     kyua_tap_summary_init(&summary);
     summary.first_index = 1;
-    summary.last_index = 7;
-    summary.ok_count = 7;
+    summary.last_index = 8;
+    summary.ok_count = 8;
     summary.not_ok_count = 0;

     ok_test(contents, &summary);
@@ -197,16 +198,17 @@
         "not ok - 1 This test failed\n"
         "ok - 2 This test passed\n"
         "not ok - 3 This test failed\n"
-        "1..5\n"
+        "1..6\n"
         "not ok - 4 This test failed\n"
-        "ok - 5 This test passed\n";
+        "ok - 5 This test passed\n"
+        "not ok - #With a test number, this test failed\n";

     kyua_tap_summary_t summary;
     kyua_tap_summary_init(&summary);
     summary.first_index = 1;
-    summary.last_index = 5;
+    summary.last_index = 6;
     summary.ok_count = 2;
-    summary.not_ok_count = 3;
+    summary.not_ok_count = 4;

     ok_test(contents, &summary);
     kyua_tap_summary_fini(&summary);
```

**Comment by ngie-eign** [comment]
This is an edge case that works, but there are others that don't work with the above regex (which is why I split it out into two regexes in my original pull request). I'm going to polish up and submit a new pull request for that today.

**Comment by jmmv** [comment]
OK, cool. BTW, teeny tiny nit:

```
-        "ok - 7 Doesn't make a difference either TODO\n";
+        "ok - 7 Doesn't make a difference either TODO\n"
+        "ok - #Without a test number is ok too\n";
```

There ought to be a space after #.

**Comment by rodrigc** [comment]
What is the best way to fix this problem?
I tried Alan's patch, and it seemed to help eliminate some false positives when running kyua against the full /usr/tests suite.

**Comment by jmmv** [comment]
I've committed a modified version of asomer's patch and the vast majority of failures in the FreeBSD test suite disappear. The remaining 3 failures are not related to this.

yaneurabeya: You mentioned that the above wasn't enough. Please indicate exactly in which case the current code still fails.

I'll get the current version of the patch added to ports so that we can give this a try on FreeBSD before I cut a new Kyua release.

**Comment by ngie-eign** [comment]
@jmmv I got bogged down with work and didn't submit a patch in time for this fix.

I'll write some additional tests to prove whether or not my hunch is valid about there being edge cases that this need to be handled differently.
