### ISSUE TITLE
kyua-plain-tester: Configuration variables not supported

### ISSUE THREAD

**Issue by rodrigc** [jmmv/kyua#104]
I tried kyua 0.10, and saw these:

kyua-plain-tester: Configuration variables not supported; ignoring
'has.cleanup=false'
kyua-plain-tester: Configuration variables not supported; ignoring
'unprivileged-user=tests'

Can kyua be changed so that these warnings are not printed out by default?
If not, how do I get rid of them?

Thanks.

**Comment by jmmv** [comment]
I'm going to close this as a duplicate of #84. The way to get rid of these warnings is to actually change Kyua to expose the configuration variables to plain test programs, and we can do so by passing the values in the environment.

**Comment by rodrigc** [comment]
Without waiting for a change to kyua itself, how can I get rid of these warnings?
A few folks have found them confusing, when looking at error output from kyua:

https://lists.freebsd.org/pipermail/freebsd-current/2014-September/052069.html

This is distracting when trying to find the source of a test failure.

**Comment by jmmv** [comment]
You can't without modifying the code in kyua/testers/. I'll get to the fixes for this in next release.
