### ISSUE TITLE
kyua --version does not report version of Kyua

### ISSUE THREAD

**Issue by rodrigc** [jmmv/kyua#110]
The following commands:

kyua --version

kyua help

Do not report the version of kyua.
It would be useful to have something that prints out the version of kyua from the command-line.

This is in kyua-0.10,2 from FreeBSD ports.

**Comment by jmmv** [comment]
Nor should they. Type `kyua about` or `kyua about version`.

**Comment by rodrigc** [comment]
"kyua about version" does print the version, but that's really not intuitive.  I would ask you to reconsider.

Several other utilities which follow the convention of [command] [verb] all support --version.  Here are a 
few examples:

pkg --version
git --version
hg --version
python --version
ruby --version

The GNU coding standards recommend "--version" to command-line utilities: http://www.gnu.org/prep/standards/html_node/_002d_002dversion.html
A lot of utilities follow this convention even if they are not GNU licensed.

**Comment by rodrigc** [comment]
Some more comments:
  If I type "kyua about", on a regular sized terminal, the version scrolls off the top of the screen, because it
  prints out the version followed by the license.

  If I type "kyua help", it is not clear to me that the "about" verb is necessary to display the version information.
  It is also not clear that in order for me to figure out how to display the version information,
  I need to type:
             kyua help
             kyua help about

   and then I need to look in the top right part of the "kyua help about" text to see that there is a "version"
   flag.

**Comment by jmmv** [comment]
Sorry but I will not add a `--version` flag. The design of such interface is broken.

See:

http://julipedia.meroh.net/2013/09/cli-design-subcommand-based-interfaces.html
http://julipedia.meroh.net/2013/09/cli-design-single-command-interfaces.html

for details.

I could reconsider displaying the version as part of `kyua help` though; that seems OKish.

**Comment by rodrigc** [comment]
Adding the version to kyua help output would be an improvement.
Also, I recommend changing:

```
about                   Shows general program information.
```

to something like:

```
about                   Shows detailed authors, license, and version information.
```

**Comment by jmmv** [comment]
OK, both suggestions sound good. Reopening to track this.
