### ISSUE TITLE
atf-run is still referenced in atf code

### ISSUE THREAD

**Issue by rodrigc** [jmmv/kyua#122]
atf-run was removed in atf-0.20, but it is still referenced internally in the code:

atf-c/detail/tp_main.c
atf-c++/tests.cpp
atf-c++/detail/process.cpp
atf-sh/libatf-sh.subr
test-programs/result_test.sh

**Comment by jmmv** [comment]
Found also a reference to atf-config in a comment.

**Comment by jmmv** [comment]
Please pay more attention to the bug tracker you use to report issues. This is an ATF issue and does not belong here.

Moved to https://github.com/jmmv/atf/issues/19 .
