### ISSUE TITLE
kyua report is missing details of test cases.

### ISSUE THREAD

**Issue by bdrewery** [jmmv/kyua#124]
I am using kyua-cli 0.8 still, sorry if it's improved already.

The output of `kyua report` is lacking all of the information about which specific test asserts failed. You must use `kyua report-html` to get the details.

<pre>
root@vbox434:/usr/tests/bin/sh/ > kyua report
===> Failed tests
legacy_test:main  ->  failed: 3 tests of 372 failed  [17.005s]
===> Summary
Action: 3
Test cases: 1 total, 0 skipped, 0 expected failures, 0 broken, 1 failed
Total time: 17.005s
</pre>

<pre>
root@vbox434:/usr/tests/bin/sh/ > kyua report-html
Generating html/context.html
Generating html/legacy_test_main.html
Generating html/report.css
Generating html/index.html
root@vbox434:/usr/tests/bin/sh/ > grep "not ok" html/*
html/legacy_test_main.html:not ok 30 - /usr/tests/bin/sh/builtins/cd1.0 # wrong exit status
html/legacy_test_main.html:not ok 33 - /usr/tests/bin/sh/builtins/cd4.0 # wrong output on stderr
html/legacy_test_main.html:not ok 254 - /usr/tests/bin/sh/expansion/pathname4.0 # wrong exit status
</pre>

It would be great if there was a way to make `kyua report` show these details. I don't have a webserver on this VM, nor my dev server to use for viewing these reports easily.

**Comment by jmmv** [comment]
This was just fixed in #49 by adding a `--verbose` flag to `kyua report`. Not yet available in a release though but should be soon.
