### ISSUE TITLE
kyua report-junit is not correctly marking skipped tests

### ISSUE THREAD

**Issue by rodrigc** [jmmv/kyua#125]
In this test run, several tests are marked as skipped:
https://jenkins.freebsd.org/jenkins/job/FreeBSD_HEAD-tests2/11/console

such as this:
local/atf/atf-c/detail/sanity_test:inv  ->  skipped: Sanity checks not available; code built with -DNDEBUG  [0.036s]

but when I look at the test report:
https://jenkins.freebsd.org/jenkins/job/FreeBSD_HEAD-tests2/11/testReport/

I don't see any tests marked in the "Skip" column.

**Comment by rodrigc** [comment]
Never mind, the tests are marked as skipped: https://jenkins.freebsd.org/jenkins/job/FreeBSD_HEAD-tests2/11/testReport/local.atf.atf-c.detail/

Please close this issue.

**Comment by jmmv** [comment]
Cool.
