### ISSUE TITLE
Remove kyua-cli from "Building from sources" part of install document

### ISSUE THREAD

**Issue by rodrigc** [jmmv/kyua#126]
I can't figure out how to issue a pull request on a github wiki page, so I am following these
steps: http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

Remove kyua-cli from "Building from sources" part of install document:
https://github.com/rodrigc/kyuawiki1/commit/993cea1a1866632a4c8735239ba527b5d266fca9

**Comment by jmmv** [comment]
It's unfortunate that there is no mechanism to do a pull request...

Incorporated this and other fixes into the page. https://github.com/jmmv/kyua/wiki/Installation/92a67b6ef45c311b8bad73139595846d9f5da784
