### ISSUE TITLE
kyua text report doesn't explain why test cases are failing

### ISSUE THREAD

**Issue by erikarn** [jmmv/kyua#131]
When I use a text output report, I don't really get any useful information about _which_ test cases are failing.

eg:

adrian@test3:~/git/gitlab/ahc/blockd/tests/libcheckstate % kyua test
norse_check_state_test:tc1  ->  passed  [0.003s]
norse_check_state_test:tc_url_blacklist_only  ->  failed: 1 checks failed; see output for more details  [0.003s]

Results file id is home_adrian_git_gitlab_ahc_blockd_tests_libcheckstate.20141027-133144-419608
Results saved to /home/adrian/.kyua/store/results.home_adrian_git_gitlab_ahc_blockd_tests_libcheckstate.20141027-133144-419608.db

1/2 passed (1 failed)
adrian@test3:~/git/gitlab/ahc/blockd/tests/libcheckstate % ./norse_check_state_test tc_url_blacklist_only
norse_check_state_test: WARNING: Running test cases without atf-run(1) is unsupported
norse_check_state_test: WARNING: No isolation nor timeout control is being applied; you may get unexpected failures; see atf-test-case(4)
**\* Check failed: norse_check_state_test.c:65: cstate.c_pass_result == NORSE_QRESULT_PASS_DEFAULT not met
failed: 1 checks failed; see output for more details

The output from the actual test case failure would be useful when running 'kyua test'.

.. then:

adrian@test3:~/git/gitlab/ahc/blockd/tests/libcheckstate % kyua report --output /tmp/foo
adrian@test3:~/git/gitlab/ahc/blockd/tests/libcheckstate % more /tmp/foo
===> Failed tests
norse_check_state_test:tc_url_blacklist_only  ->  failed: 2 checks failed; see output for more details  [0.003s]
===> Summary
Results read from /home/adrian/.kyua/store/results.home_adrian_git_gitlab_ahc_blockd_tests_libcheckstate.20141027-132659-061718.db
Test cases: 2 total, 0 skipped, 0 expected failures, 0 broken, 1 failed
Total time: 0.005s

**Comment by jmmv** [comment]
`kyua report` has a `--verbose` flag in 0.11 which shows the information you are looking for. I should be able to commit the relevant package updates to ports tomorrow or so.
