### ISSUE TITLE
kyua-testers cannot be cross compiled due to the getcwd(NULL, 0) test

### ISSUE THREAD

**Issue by jmmv** [jmmv/kyua#71]
_From [xtraeme](https://code.google.com/u/106812073015308749022/) on November 03, 2013 02:42:52_

I made a commit to the kyua-testers repository and it's stored temporarily in
the xbps-packages repo to allow successful cross compilation (it has been successfully cross compiled for arm).

Commit/patch attached to allow configure caching of getcwd(NULL, 0) test.

Please apply this one for 0.2, thanks.

**Attachment:** [0001-Cache-configure-result-of-getcwd-NULL-0-test.patch](http://code.google.com/p/kyua/issues/detail?id=71)

_Original issue: http://code.google.com/p/kyua/issues/detail?id=71_

**Comment by ngie-eign** [comment]
Is AC_MSG_RESULT(no) getting lost in the patch, i.e. does it output a sane "yes it works" or "no it doesn't work message"?

**Comment by jmmv** [comment]
kyua-testers and kyua-cli are now the same module and they share the same m4 code, so closing this in favor of #72.
