### ISSUE TITLE
rewrite__expected_signal__bad_arg fails on linux

### ISSUE THREAD

**Issue by jmmv** [jmmv/kyua#75]
_From [asomers](https://code.google.com/u/118332783231543903398/) on December 22, 2013 00:31:25_

What steps will reproduce the problem? 1. cd /usr/local/tests/kyua-testers
2. kyua test atf_result_test:rewrite__expected_signal__bad_arg What is the expected output? What do you see instead? The test expects to see this string in out.txt:
broken: Invalid status argument (abc): not a number; test case received signal 25\n
But it actually received this one:
broken: Invalid status argument (abc): not a number; test case received signal 25 (core dumped) What version of the product are you using? On what operating system? kyua-testers 892c8f1a65bcf43174bc7d8301a949445c5b6a19
kyua-cli d5efdc8eebc0ea0f78036230defccf8bd23e9b08
Ubuntu 12.04 amd64
$ uname -a
Linux lilo 3.2.0-57-generic #87-Ubuntu SMP Tue Nov 12 21:35:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux Please provide any additional information below. The failure is caused by different default behavior for SIGXFSZ on NetBSD vs Linux.  On NetBSD and FreeBSD, SIFXFSZ terminates the process.  However, on Linux SIFXFSZ dumps core.  The test failure is caused by the core dump when none was expected.  However, that's not really what this test was designed to check.  The rest of the message is correct.  I suggest changing the signal from 25 (SIGXFSZ) to 15 (SIGTERM) which is handled identically by BSD and Linux.  Patch attached. http://netbsd.gw.com/cgi-bin/man-cgi?signal+7+NetBSD-current http://www.freebsd.org/cgi/man.cgi?query=signal&apropos=0&sektion=0&manpath=FreeBSD+9.2-RELEASE&arch=default&format=html http://man7.org/linux/man-pages/man7/signal.7.html

**Attachment:** [0001-Fix-rewrite__expected_signal__bad_arg-on-Linux.patch](http://code.google.com/p/kyua/issues/detail?id=75)

_Original issue: http://code.google.com/p/kyua/issues/detail?id=75_

**Comment by ngie-eign** [comment]
The patch should use the symbolic name for SIGTERM, not 15.
