### ISSUE TITLE
Supported metadata isn't documented; not provided in examples

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#80]
Certain metadata like required_files, required_memory, etc isn't documented in kyua.conf(5) and isn't available in the examples. It would be nice if we had this so other developers knew what metadata was available when setting requirements for tests.

**Comment by jmmv** [comment]
The metadata belongs to the Kyuafile, not kyua.conf. kyuafile(5) contains this reference:

_Please see kyua-tester-list(5) for the list of metadata properties that can be given to test programs.  All the properties that can be given to a test case can also be given to a test program._

and the referenced manual page includes the requested details.
