### ISSUE TITLE
"Committed action <id>" could be more intuitive

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#82]
At the end of each test run the message:

<pre>
Committed action &lt;id&gt;
</pre>

is printed out. It would be nicer if it printed out something else like:

<pre>
Completed test job &lt;id&gt;
</pre>

Or the term "action" and/or the database commit process was a bit more thoroughly documented in "man kyua".

**Comment by jmmv** [comment]
This is not applicable any longer. The term "action" has been completely removed in 0.9 and the test command now prints both the run identifier and the file to which the data was saved.
