### ISSUE TITLE
kyua-testers: TAP parser only supports `ok`/`not ok` results in the TAP protocol

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#85]
The complete list of potential results for the TAP protocol is not well-formed, but it includes:
- "ok"
- "ok # TODO (optional-message)"
- "not ok"
- "not ok # TODO (optional-message)"
- "# SKIP"

This should probably work out to be:
- "ok" should map to "atf_tc_pass"
- "ok # TODO (optional-message)" "atf_tc_pass"
- "not ok" should map to "atf_tc_fail"
- "not ok # (TODO) (optional-message)" should map to "atf_tc_fail_nonfatal"?
- "# SKIP" should map to "skip".

This is picked out of comments in the testcase line. Example:

<pre>
% cat ~/test_skip.sh
#!/bin/sh
echo '1..0 # skip all the things'
% prove -v ~/test_skip.sh
/root/test_skip.sh ..
1..0 # skip all the things
skipped: all the things
Files=1, Tests=0,  0 wallclock secs ( 0.04 usr +  0.01 sys =  0.05 CPU)
Result: NOTESTS
</pre>

1. http://perldoc.perl.org/TAP/Parser/Result/Test.html
2. https://github.com/petere/pex/blob/master/t/libtap.sh
3. http://www.eyrie.org/~eagle/software/c-tap-harness/writing.html
4. http://www.eyrie.org/~eagle/software/c-tap-harness/

**Comment by ngie-eign** [comment]
Here's the full grammar, but the markup's a bit confusing (and potentially incorrect .. need to test the markup to make sure that my understanding's correct): http://perldoc.perl.org/TAP/Parser/Grammar.html

**Comment by ngie-eign** [comment]
Not fully supporting the TAP protocol is why one of the testcases currently fails on FreeBSD 11-CURRENT: http://kyua3.nyi.freebsd.org/head/data/0-LATEST/results/usr.bin_sed_multi_test_main.html

**Comment by jmmv** [comment]
Oh cool, so you found the (or should I say "a"?) grammar! I was unable to do so...

I think the right mapping for the TODOs should be expected failure, but I'm not sure. What's the point of TODO test cases anyway?

Did you remove the `not ok (unplanned)` from the bug? I can see that in the email copy I got but not here nor in the grammar. If it is indeed a possibility, this should map to broken.

**Comment by jmmv** [comment]
Scratch that. We cannot make mappings to things other than pass or fail.

The whole TAP test program is executed at once, so when parsing its output, we have to determine whether the whole program passed or failed. So yes, your original proposed mapping makes sense and should be a trivial modification.

**Comment by ngie-eign** [comment]
Yeah, but the grammar page is a bit confusing/buggy. The best resource I found (if you can read perl) is the source code. I can't find a link to it, but it's basically TAP/Parser/Grammar.pm (here's a snippet from 5.14 as a reference):

<pre>        test => {
            syntax  => qr/^($ok) \s* ($num)? \s* (.*) \z/x,
            handler => sub {
                my ( $self, $line ) = @_;
                my ( $ok, $num, $desc ) = ( $1, $2, $3 );
                my ( $dir, $explanation ) = ( '', '' );
                if ($desc =~ m/^ ( [^\\\#]* (?: \\. [^\\\#]* )* )
                       \# \s* (SKIP|TODO) \b \s* (.*) $/ix
                  )
                {
                    ( $desc, $dir, $explanation ) = ( $1, $2, $3 );
                }
                return $self->_make_test_token(
                    $line, $ok, $num, $desc,
                    $dir,  $explanation
                );
            },
        },
</pre>

**Comment by jmmv** [comment]
Let's actually reopen this given that I missed support for "skip plans" (dunno what they are yet). If you can clean up your pull request for this, that'd be great.

By the way, regarding the grammar: I have seen so many different descriptions of the TAP format (both formal and informal) that I think sticking to a specific grammar is going to be harmful. We should be very loose in what we accept, both for simplicity and compatibility. Anything that more or less looks like what the grammar describes should be accepted as valid TAP (as I did, e.g. with SKIP and TODO by only checking if those words appear anywhere in the test result line).

(After all, the use case we are mostly trying to support are the hand-crafted TAP test programs in the old FreeBSD tests... and those are more often than not broken anyway.)

**Comment by ngie-eign** [comment]
I completely agree. That's part of the reason why I added the regular expression checking in tap_helper.c to just catch these cases (we should definitely discuss this further in person this week though while you're in town).

Thanks :)!

**Comment by jmmv** [comment]
Ah no, I see you already opened #86 for skip plans. Reclosing this.
