### ISSUE TITLE
atf-sh -h doesn't do anything

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#89]
The manpage says that atf-sh -h does the following:

`-h    Shows a short summary of all available options and their purpose.`

However, atf-sh -h says the option's unknown:

<pre>
% /usr/local/bin/atf-sh -h
atf-sh: ERROR: Unknown option -h.
atf-sh: See atf-sh(1) for usage details.
% man atf-sh
ATF-SH(1)               FreeBSD General Commands Manual              ATF-SH(1)

NAME
     atf-sh -- interpreter for shell-based test programs

SYNOPSIS
     atf-sh script
     atf-sh -h

DESCRIPTION
     atf-sh is an interpreter that runs the test program given in script after
     loading the atf-sh-api(3) library.

     atf-sh is not a real interpreter though: it is just a wrapper around the
     system-wide shell defined by the `atf_shell' configuration value in
     atf-config(1).  atf-sh executes the interpreter, loads the atf-sh-api(3)
     library and then runs the script.

     Scripts using atf-sh-api(3) should start with:

           #! /usr/bin/env atf-sh

     The following options are available:

     -h    Shows a short summary of all available options and their purpose.

SEE ALSO
     atf-config(1), atf-sh-api(3), atf(7)

FreeBSD 10.0                   October 15, 2013                   FreeBSD 10.0

% pkg info | grep atf
atf-0.20_1                     C, C++ and shell libraries to write ATF-compliant test programs
kyua-atf-compat-0.2_2          Kyua (automated testing framework) - ATF compatibility tools
% uname -a
FreeBSD freebsd-10-x64.localdomain 10.0-STABLE FreeBSD 10.0-STABLE #0 7905925(stable/10): Wed Jun 11 14:10:17 PDT 2014     root@freebsd-x86.localdomain:/usr/obj/usr/src/sys/GENERIC-WITHOUT-WITNESS  amd64
%
</pre>

**Comment by jmmv** [comment]
This is for atf. Not applicable here.

**Comment by jmmv** [comment]
FYI, refiled under https://github.com/jmmv/atf/issues/9 .
