### ISSUE TITLE
TAP parser: "broken: Reported plan differs from actual executed tests"

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#90]
prove can run the closefrom testcase, but the TAP parser in kyua doesn't seem to be capable of handling the output:

<pre>% prove -v ./closefrom
./closefrom ..
1..15
ok 1 - open
ok 2 - highest_fd
ok 3 - closefrom
ok 4 - open 16
ok 5 - closefrom
ok 6 - close 2
ok 7 - close(6)
ok 8 - close(8)
ok 9 - closefrom
ok 10 - mmap
ok 11 - closefrom(0)
ok 12 - closefrom(-1)
ok 13 - dup2
ok 14 - closefrom
ok 15 - closefrom
ok
All tests successful.
Files=1, Tests=15,  0 wallclock secs ( 0.03 usr +  0.02 sys =  0.05 CPU)
Result: PASS
% kyua test
closefrom:main  ->  broken: Reported plan differs from actual executed tests  [0.008s]

0/1 passed (1 failed)
Committed action 45
</pre>

**Comment by ngie-eign** [comment]
It's printing out "ok" at the bottom which is confusing the parser:

<pre>
270         else if (strstr(line, "ok") == line)
271             summary->ok_count++;
272         else if (strstr(line, "not ok") == line)
273             summary->not_ok_count++;
274         else if (strstr(line, "SKIP") == line)
275             summary->not_ok_count++;
</pre>

The parser needs to implement more complex regular expression checking for the results.

**Comment by jmmv** [comment]
Closed in 5f6a671.

Looks like the syntax I used in the commit message was not goog enough to be picked up by GitHub...
