### ISSUE TITLE
stpncpy support should fall back to strncpy if stpncpy doesn't exist

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#99]
I recently tried to compile kyua-testers from git on FreeBSD 7, which doesn't have stpncpy support (it was added in 8.x), and I ran into build errors. It would be nice if there was an autoconf test and the code fell back to logic that involved strncpy+strlen (to get to the end of the buffer).

This code hasn't been released yet.

**Comment by jmmv** [comment]
The question I always have in these cases: do we want to get into the business of supporting obsolete operating systems not supported by upstream? Where do we draw the line of what's acceptable and what not?

I'm leaning towards _no_ as I'd actually like us moving towards more modern features (e.g. C++11) instead.

**Comment by jmmv** [comment]
Over a month without feedback, so closing with the current rationale of not wanting to support abandoned OS releases. Please reopen if you disagree.

**Comment by ngie-eign** [comment]
FreeBSD 7.x is dead. Might as well move forward because keeping backwards compatibility doesn't make sense..
